### PR TITLE
Fix verify signature double negation

### PR DESCRIPTION
**Pull request by felixarjuna**
I want to fix the verifyRequestSignature method inside `index.ts` file. From the jsdoc docs,  the returnred boolean value should indicate that the signature is valid. Hope it helps! :) 

### PR Checklist

-   [x] It's really useful if your PR references an issue where it is discussed ahead of time.
-   [x] This message body should clearly illustrate what problems it solves.
-   [-] Ideally, include a test that fails without this PR but passes with it.

### Tests

-   [-] Run the tests with `npm run test` and lint the project with `npm run lint` and `npm run prettier`

### CODE REVIEW

**Comment by Secreto31126** [comment]
Hm, this is really big if true. If your change does pass the tests, not only it means the whole library was broken, but also the unit tests failed to catch the issue. I can't believe this went thru so easily.

**Review by limck5856 — COMMENTED** [review]
Review

**Comment by Secreto31126** [comment]
Hey @felixarjuna, sorry for the harsh reply last week, I got a little too annoyed/scared/excited about the first vulnerability on the library :)

I added you as the finder on the CVE and in the README. Really thankful for your PR and raising this bug, which allowed any payload _except real WhatsApp's_ to be processed. I will try to get some time to fix the unit tests in order to avoid similar dumb issues in the future.

Thanks!

**Comment by felixarjuna** [comment]
I‘m really happy, that it really helped. 🙂

**Pull request merged**
