### PR TITLE
Handle Unicode characters

### LINKED ISSUE #290: 401 error on post with special characters
**Describe the bug**
When I send a message to the API containing special characters, for example "J'ai mangé des pâtes", the post request responds a 401 error.

### PR DESCRIPTION
**Pull request by Secreto31126**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:

-   [x] It's really useful if your PR references an issue where it is discussed ahead of time.
-   [x] This message body should clearly illustrate what problems it solves.
-   [x] Ideally, include a test that fails without this PR but passes with it.

### Tests

-   [x] Run the tests with `npm run test` and lint the project with `npm run lint` and `npm run prettier`

Closes #290

### CODE REVIEW

**Comment by YacineMessaadi** [comment]
Hi @Secreto31126, thank you so much for the work !
Can you make an alpha release for this feature ? I have to use it soon please 🙏

**Comment by Secreto31126** [comment]
Ok, I can make it 2.5.0-beta.0, give me one sec

**Comment by Secreto31126** [comment]
It's ready, the action is finishing the release. You can install it with:

```shell
npm i whatsapp-api-js@beta
```

**Comment by YacineMessaadi** [comment]
Nice! It works! Thanks 🥳

**Comment by Secreto31126** [comment]
Awesome! A stable release will be done when I get confirmation the other PR works as expected.

**Pull request merged**
