### PR TITLE
Fix get params field

### PR DESCRIPTION
**Pull request by lybrus**

### CODE REVIEW

**Comment by Secreto31126** [comment]
Hmm, I just noticed that your `post()` and `get()` recieve the http request directly, and assumes that `query`, `body` and a few other methods exists. I don't fully agree on this, mostly because it's presuming a standard. I would rather let the user pick how to process the required data rather than doing it internally.

Anyway, I will merge the pull for the sake of bug-free code.

PS: You might be interested in reading the branch typescript. It's not yet done, but I'm rounding up the last changes.

**Comment by lybrus** [comment]
Yeah, I agree. I should be some helpers: expressMiddlewares, nestjs module, etc. For now, I'm using these methods with nestjs.

Regarding Typescript - it's what I lack! I'll check it later. I really like this undertaking. I have some experience in writing API libraries. In one library I implemented a layer for DTO objects. Corns:

*   You can use JS-adopted objects (camel case for field names, classes, etc...)
*   Automatic serialization. For dates for example
*   Autogenerated fields
*   etc...

You can explore it here [https://github.com/lybrus/amocrm-connector/tree/master/src/core/AmoDTO](https://github.com/lybrus/amocrm-connector/tree/master/src/core/AmoDTO)

Usage examples:

[https://github.com/lybrus/amocrm-connector/blob/master/src/subsystems/Chat/Message/AddMessagePayload.ts](https://github.com/lybrus/amocrm-connector/blob/master/src/subsystems/Chat/Message/AddMessagePayload.ts)

this class automatically converts to https://www.kommo.com/developers/content/chats/sending-importing-messages/ (Payload elements)

Using the AmoLike type you can provide an instance of a generic class, an array of this type, or a deep partial plain object/array with fields autocompleting/checking in an IDE.

https://github.com/lybrus/amocrm-connector/blob/master/src/subsystems/Chat/Chat.ts#L76

**Comment by Secreto31126** [comment]
Thanks for the tips and the code examples, I didn't know I could use index.ts within a subfolder to allow exporting all the types inside the folder, it works perfectly for the messages classes

**Comment by lybrus** [comment]
If you wanna discuss it feel free to chat me tg, the same nickname as here.

**Pull request merged**
