### PR TITLE
Lockfile removal

### PR DESCRIPTION
**Pull request by Secreto31126**
### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:

-   [ ] It's really useful if your PR references an issue where it is discussed ahead of time.
-   [ ] This message body should clearly illustrate what problems it solves.
-   [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests

-   [ ] Run the tests with `npm run test` and lint the project with `npm run lint` and `npm run prettier`

I expect you to fail

### CODE REVIEW

**Comment by Secreto31126** [comment]
image

**Comment by Secreto31126** [comment]
I'm sorry @ekoeryanto, but even actions/setup-node fails to initialize if the lockfile is missing. Afaik there's no alternative to this, and I can't undergo through a full actions rewrite.

I would still love to understand _why_ this was important to you, since the file is only required on dev side, it shouldn't impact on the runtime agnostic philosophy of the package.

Thanks anyway!

**Comment by Secreto31126** [comment]
Ok, feel free to keep working on this branch, if I like your fix we can open a new PR then

**Comment by ekoeryanto** [comment]
https://github.com/pakeweb/whatsapp-api-js/actions/runs/8562335063

**Comment by ekoeryanto** [comment]
with npm https://github.com/pakeweb/whatsapp-api-js/actions/runs/8562398049

**Comment by Secreto31126** [comment]
Wow, that's actually really cool! I like the idea of testing with different runtimes (I can try adding Deno too). There's one last thing I would like to know, is removing the lockfile still necesary? I can see in your demo package-lock.json is still there, and all the actions finished successfully. What's more, bun even detected the lockfile and migrated it to its own lockfile format (took 3 seconds to do so, but not a big deal).

If possible, could you run the action again without the lockfile too? I just want to make sure it won't break everything else in the project.

Seriously, many thanks for your time :)

**Comment by ekoeryanto** [comment]
_is removing the lockfile still necesary?_

actually, no. but best practice with public repo (my thought) is not forcing to only npm. 1 more advantage is the deps are keep updated/monitored based on semver on package.json.

_Deno?_
there's nothing limit us ;-)

Sorry for not PRing this, you can just simply copy-pasted the yml

**Pull request closed without merging**
